name: rbt_sc
channels:
  - conda-forge
  - defaults
  - materials-project
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  - jupyter>=1.0.0
  - ipykernel
  - pymatgen>=2022.7.19
  - ase>=3.22.0
  - spglib>=1.16.0
  - networkx>=2.6.0
  - plotly>=5.0.0
  - seaborn>=0.11.0
  - openpyxl>=3.0.0
  - xlsxwriter>=3.0.0
  - tqdm>=4.62.0
  - click>=8.0.0
  - pip
  - pip:
    - qe-tools>=2.0.0
    - crystal-toolkit>=0.9.0
    - mp-api>=0.33.0 