name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install package (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run pytest with coverage
        run: pytest -q --cov=scripts --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml 